// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVZh0m0GW8__sayXqA8HJ5BtIYzXBIzk',
    appId: '1:59441920882:web:23af480ac12c447b477beb',
    messagingSenderId: '59441920882',
    projectId: 'texibooking-26657',
    authDomain: 'texibooking-26657.firebaseapp.com',
    storageBucket: 'texibooking-26657.firebasestorage.app',
    measurementId: 'G-DBFSWQLZHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE4QYD7t9KTTG-K9cz8uw9Seyd3iIIq8c',
    appId: '1:59441920882:android:b2dba4f434ce4b4a477beb',
    messagingSenderId: '59441920882',
    projectId: 'texibooking-26657',
    storageBucket: 'texibooking-26657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwaEVQ5JPWlXehIypwv8g5vfnU3t12ZQ0',
    appId: '1:59441920882:ios:a649ad698facf967477beb',
    messagingSenderId: '59441920882',
    projectId: 'texibooking-26657',
    storageBucket: 'texibooking-26657.firebasestorage.app',
    iosBundleId: 'com.example.dohaGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwaEVQ5JPWlXehIypwv8g5vfnU3t12ZQ0',
    appId: '1:59441920882:ios:a649ad698facf967477beb',
    messagingSenderId: '59441920882',
    projectId: 'texibooking-26657',
    storageBucket: 'texibooking-26657.firebasestorage.app',
    iosBundleId: 'com.example.dohaGraduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfVZh0m0GW8__sayXqA8HJ5BtIYzXBIzk',
    appId: '1:59441920882:web:67623112958695c5477beb',
    messagingSenderId: '59441920882',
    projectId: 'texibooking-26657',
    authDomain: 'texibooking-26657.firebaseapp.com',
    storageBucket: 'texibooking-26657.firebasestorage.app',
    measurementId: 'G-5MNQ58KP4R',
  );
}
