name: Flutter - Android Build APK & App Bundle

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 📥 Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # ☕ Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # 🐦 Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 📦 Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 🔐 Decode keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      # 🔐 Decode key.properties
      - name: Decode key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_BASE64 }}" | base64 --decode > android/key.properties

      # 🧱 Build APK (Obfuscated)
      - name: Build APK
        run: flutter build apk

      # 📦 Build AAB (Obfuscated)
      - name: Build App Bundle
        run: flutter build appbundle

      # 📤 Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: user-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 📤 Upload AAB
      - name: Upload User AAB
        uses: actions/upload-artifact@v4
        with:
          name: user-aab
          path: build/app/outputs/bundle/release/app-release.aab

